---
- hosts: all
  become: true
  pre_tasks:
    #- name: update system
    #  yum: name=* state=latest
    - name: ensure packages required are installed
      yum: pkg={{item}} state=latest
      with_items:
        - vim
        - bc
        - unzip
    #- name: Install unrar if it is not installed
    #  command: yum install {{unrar_url}} --nogpgcheck creates=/usr/bin/unrar
    #  ignore_errors: True
    #- name: test unrar
    #  unarchive: src={{test_url}} dest=/tmp/test1 copy=no
  roles:
    - williamyeh.oracle-java
    - ansible-zookeeper
    - ansible-storm
    #- liquibase
    #- jboss
  vars:
    java_version: 7
    java_download_from_oracle: true
    java_remove_download: false
    java_subversion: 80
    storm_nimbus_enabled: true
    storm_supervisor_enabled: true
    storm_ui_enabled: true
    nimbus_host: "{{ansible_host}}"
    storm_ui_host: "{{ansible_host}}"
    storm_logviewer_enabled: true
    zookeeper_hosts:
      - {host: "{{ansible_host}}", id: 1}
