---
- hosts: all
  become: true
  tasks:
    #- name: update system
    #  yum: name=* state=latest
    - name: ensure packages required are installed
      yum: pkg={{item}} state=latest
      with_items:
        - vim
        - bc
        - unzip
    #- name: Install unrar if it is not installed
    #  command: yum install {{unrar_url}} --nogpgcheck creates=/usr/bin/unrar
    #  ignore_errors: True
    #- name: test unrar
    #  unarchive: src={{test_url}} dest=/tmp/test1 copy=no
  roles:
    - williamyeh.oracle-java
    - liquibase
    #- jboss
  vars:
    java_version: 7
    java_download_from_oracle: true
    java_remove_download: false
    java_subversion: 80
    test_url: http://10.211.55.2:8000/test.rar
    #unrar_url: http://10.211.55.2:8080/unrar-5.2.3-1.gf.el6.x86_64.rpm
    unrar_url: http://packages.psychotic.ninja/6/base/x86_64/RPMS/unrar-5.2.4-2.el6.psychotic.x86_64.rpm
    #jdk_tarball_url:  http://10.211.55.2:8080/jdk-7u80-linux-x64
