---
- hosts: all
  become: true
  tasks:
    #- name: update system
    #  yum: name=* state=latest
    - name: ensure packages required are installed
      yum: pkg={{item}} state=latest
      with_items:
        - vim
        - bc
        - unzip
    - name: Check if unrar is installed
      command: rpm -q unrar
      register: unrar_rpm_check
    - name: Install unrar if it is not installed
      yum: name={{unrar_url}} disable_gpg_check=yes
      when: unrar_rpm_check.stdout.find('is not installed') != -1
    #- name: test unrar
    #  unarchive: src={{test_url}} dest=/tmp/test1 copy=no
  roles:
    - williamyeh.oracle-java
    - jboss
  vars:
    java_version: 7
    java_download_from_oracle: true
    java_remove_download: false
    java_subversion: 80
    test_url: http://10.211.55.2:8000/test.rar
    unrar_url: http://10.211.55.2:8080/unrar-5.2.3-1.gf.el6.x86_64.rpm
    jdk_tarball_url:  http://10.211.55.2:8080/jdk-7u80-linux-x64
