---
- hosts: all
  become: true
  pre_tasks:
    - name: ensure packages required are installed
      yum: pkg={{item}} state=latest
      with_items:
        - vim
        - bc
        - unzip
        - nc
        - telnet
    #- shell: echo {{groups['mq']}}
    #"{{ hostvars[groups['oracle'][0] if 'oracle' in groups else groups['all'][0]]['ansible_host'] | default('10.21.25.212')}}"
  roles:
    - ansible-oracle-java
  vars:
    java_version: 7
    java_download_from_oracle: true
    java_remove_download: false
    java_subversion: 80
- hosts: zookeeper
  become: true
  roles:
    - ansible-zookeeper
  vars:
    zookeeper_hosts:
      - {host: 192.168.50.2, id: 1}
- hosts: storm
  become: true
  roles:
    - ansible-storm
  vars:
    storm_supervisor_enabled: true
    nimbus_host: 192.168.50.2
    storm_nimbus_enabled: nimbus_host in ansible_all_ipv4_addresses
    storm_ui_host: 192.168.50.2
    storm_ui_port: 8088
    storm_ui_enabled: storm_ui_host in ansible_all_ipv4_addresses
    storm_logviewer_enabled: true
    zookeeper_hosts:
      - {host: 192.168.50.2, id: 1}
