---
- hosts: all
  become: true
  tasks:
    - name: update system
      yum: name=* state=latest
    - name: ensure packages required are installed
      yum: pkg={{item}} state=latest
      with_items:
        - vim
        - bc
        - unzip
    - name: install unrar
      yum: name=http://mirror.symnds.com/distributions/gf/el/6/gf/x86_64/unrar-5.2.3-1.gf.el6.x86_64.rpm disable_gpg_check=yes state=present
    - name: test unrar
      unarchive: src=files/test.rar dest=/tmp/
  roles:
    - williamyeh.oracle-java
  vars:
    java_version: 7
    java_download_from_oracle: true
    java_remove_download: false
    java_subversion: 80
