---
- name: Create Liquibase directory
  file: name=/opt/liquibase state=directory mode=0755 owner=root group=root

- name: Install Liquibase
  unarchive:
    src: "{{liquibase_src}}"
    dest: /opt/liquibase
    copy: no
    owner: root
    group: root
    mode: 0755
    creates: /opt/liquibase/liquibase
